version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5502:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: crow_openbareruimte
      POSTGRES_USER: crow_openbareruimte
  importer:
    build: importer
    links:
      - database
    command: >
        bash -c "/app/docker-run.sh"
    environment:
      OBJECTSTORE_PASSWORD: